export const tr = (en, hans, hant) => ({ en, 'zh-Hans': hans, 'zh-Hant': hant });
export const ui = {
  portfolio: tr('A PERSONAL ENGINEERING PORTFOLIO','个人技术作品集','個人技術作品集'),
  skip: tr('Skip to content','跳转到正文','跳至正文'),
  choose: tr('Choose language','选择语言','選擇語言'),
  name: tr('Tenghui Tu','涂腾辉','涂騰輝'),
  field: tr('EMBEDDED SYSTEMS & BEYOND','嵌入式开发与工程实践','嵌入式開發與工程實踐'),
  direction: tr('Embedded Development · Computer Vision\nHMI & System Integration','嵌入式开发 · 机器视觉\nHMI 与系统集成','嵌入式開發 · 機器視覺\nHMI 與系統整合'),
  intro: tr('I bring software and hardware together. From interactive devices to robotic systems, I work on the details that make things work.','我专注于嵌入式软件与硬件的协同。从交互设备到机器人系统，在控制、通信与联调中，让想法成为可以运行的实物。','我專注於嵌入式軟體與硬體的協同。從互動裝置到機器人系統，在控制、通訊與整合測試中，讓想法成為可以運行的實物。'),
  projectsLink: tr('Explore my work','查看技术项目','查看技術專案'),
  cv: tr('Download CV','下载简历','下載履歷'),
  student: tr('Hunan Agricultural University','湖南农业大学 · 本科在读','湖南農業大學 · 本科在學'),
  portrait: tr('Portrait of Tenghui Tu','涂腾辉证件照','涂騰輝證件照'),
  selectedLabel: tr('01 / SELECTED WORK','01 / 精选项目','01 / 精選專案'),
  selected: tr('Built to work.','让技术落到实处。','讓技術落到實處。'),
  all: tr('All engineering projects','全部技术项目','全部技術專案'),
  skillsLabel: tr('02 / TECHNICAL FOUNDATION','02 / 技术能力','02 / 技術能力'),
  skillsTitle: tr('From signals\nto systems.','从信号，\n到系统。','從訊號，\n到系統。'),
  skillsIntro: tr('A practical toolkit, developed through code, prototypes, and hands-on integration. Every capability connects to a real project.','在代码、原型和实机联调中积累技术能力。每一项能力，都对应具体的工程实践。','在程式碼、原型和實機整合測試中累積技術能力。每一項能力，都對應具體的工程實踐。'),
  viewCase: tr('Explore the project ↗','查看对应项目 ↗','查看對應專案 ↗'),
  experienceLabel: tr('03 / ENGINEERING EXPERIENCE','03 / 工程实习','03 / 工程實習'),
  experience: tr('Beyond the workbench.','走向真实应用。','走向真實應用。'),
  experienceIntro: tr('Working with real devices, real constraints, and engineering teams.','走进实际设备、现场环境与工程团队。','走進實際裝置、現場環境與工程團隊。'),
  leadershipLabel: tr('04 / LEADERSHIP & COLLABORATION','04 / 领导与协作','04 / 領導與協作'),
  leadership: tr('Building, together.','一起，把事情做好。','一起，把事情做好。'),
  leadershipOne: tr('Interactive tabletop project lead','智能桌游项目负责人','智慧桌遊專案負責人'),
  leadershipOneBody: tr('Coordinate product planning, embedded implementation, and hardware integration. Connect the work of teammates while contributing directly to the technical build.','统筹产品方案、嵌入式实现与软硬件协作，在承担技术工作的同时，协调团队分工、联调与展示准备。','統籌產品方案、嵌入式實作與軟硬體協作，在承擔技術工作的同時，協調團隊分工、整合測試與展示準備。'),
  leadershipTwo: tr('Research & campus collaboration','实验室与校园协作','實驗室與校園協作'),
  leadershipTwoBody: tr('An undergraduate member of the Agricultural AI Laboratory and vice president of the Smart Agriculture Association. Support project collaboration and coordinate work across teams.','作为农业人工智能实验室本科生成员、智慧农业协会副会长，参与项目协作，协调部门分工与团队事务。','作為農業人工智慧實驗室本科生成員、智慧農業協會副會長，參與專案協作，協調部門分工與團隊事務。'),
  contactLabel: tr('LET’S CONNECT','联系我','聯絡我'),
  contactTitle: tr('Good things start\nwith a conversation.','好的合作，\n从一次交流开始。','好的合作，\n從一次交流開始。'),
  contactBody: tr('For engineering opportunities, project collaboration, or a conversation about how things work.','欢迎交流技术岗位、工程项目与合作机会。','歡迎交流技術職位、工程專案與合作機會。'),
  combined: tr('Trilingual CV','三语合并简历','三語合併履歷'),
  other: tr('Other work','其他作品','其他作品'),
  top: tr('Back to top ↑','回到顶部 ↑','回到頂部 ↑'),
  back: tr('← Back to home','← 返回首页','← 返回首頁'),
  backProjects: tr('← All projects','← 全部项目','← 全部專案'),
  archiveTitle: tr('Engineering,\nin practice.','技术，在实践中。','技術，在實踐中。'),
  archiveIntro: tr('Interactive devices, control systems, and hardware experiments. A collection of what I have built and the part I played in making it work.','交互设备、控制系统与硬件实践。这里记录我做过的项目，以及其中由我承担的具体工作。','互動裝置、控制系統與硬體實踐。這裡記錄我做過的專案，以及其中由我承擔的具體工作。'),
  projectLabel: tr('ENGINEERING PROJECT','技术项目','技術專案'),
  contribution: tr('My contribution','我的技术贡献','我的技術貢獻'),
  stack: tr('Focus & tools','技术方向与工具','技術方向與工具'),
  context: tr('The project','项目背景','專案背景'),
  implementation: tr('How it works','技术实现','技術實作'),
  evidence: tr('On the workbench','实物与过程','實物與過程'),
  notes: tr('Outcomes & collaboration','成果与协作','成果與協作'),
  source: tr('View source on GitHub','在 GitHub 查看源码','在 GitHub 查看原始碼'),
  contents: tr('IN THIS PROJECT','项目内容','專案內容'),
  related: tr('Keep exploring.','继续探索。','繼續探索。'),
  diagram: tr('CONTROL ARCHITECTURE','控制结构示意','控制結構示意'),
  feedback: tr('encoder feedback','编码器反馈','編碼器回授'),
  loopLabel: tr('STM32 · CLOSED-LOOP SPEED CONTROL','STM32 · 速度闭环控制','STM32 · 速度閉迴路控制'),
  conceptual: tr('Architecture illustration','技术结构示意','技術結構示意'),
  otherIntro: tr('Alongside engineering, I have contributed to agricultural equipment films through AI-generated assets, sound, and editing. The two films below were adopted by a partner company.','工程之外，我也参与农业设备宣传片制作，负责素材生成、音轨铺设与剪辑。以下两部作品已被合作公司认可并采用。','工程之外，我也參與農業設備宣傳片製作，負責素材生成、音軌鋪設與剪輯。以下兩部作品已被合作公司認可並採用。'),
  teaOne: tr('Tea-harvesting equipment · Promotional film','茶叶采摘设备 · 宣传片','茶葉採摘設備 · 宣傳片'),
  teaTwo: tr('Tea-withering equipment · Promotional film','茶叶萎凋设备 · 宣传片','茶葉萎凋設備 · 宣傳片'),
  notFound: tr('This page has moved.','没有找到这个页面。','找不到這個頁面。'),
  notFoundBody: tr('Explore the project collection or return to the homepage.','可以返回首页，或浏览全部技术项目。','可以返回首頁，或瀏覽全部技術專案。'),
  openImage: tr('Open full-size image','查看完整图片','查看完整圖片'),
  clip: tr('Prototype demonstration','原型演示','原型展示'),
};

export const projects = [
  {
    id:'emotion-screen', index:'01', kind:'badge', image:'badge.jpg',
    title:tr('Interactive electronic badge','电子吧唧交互终端','電子徽章互動終端'),
    short:tr('Turning motion into expression, with embedded media and real-time interaction.','通过动作触发表情与音效，协调实时交互、媒体播放与存储。','透過動作觸發表情與音效，協調即時互動、媒體播放與儲存。'),
    role:tr('Software development & hardware integration','软件研发与软硬件联调','軟體研發與軟硬體整合測試'),
    tags:['ESP32-S3','FreeRTOS','C'], source:'https://github.com/titfly77-cyber/emotion_screen',
    context:tr('An interactive screen device that changes expressions and sound effects in response to physical interactions. I led the software development and worked on hardware integration.','通过不同交互动作实现表情切换与音效变化的屏幕设备。我负责软件研发，并配合硬件完成设备联调。','透過不同互動動作實現表情切換與音效變化的螢幕裝置。我負責軟體研發，並配合硬體完成裝置整合測試。'),
    contributions:[tr('Develop the embedded interaction logic and coordinate display, audio, sensor input, and storage.','开发嵌入式交互逻辑，协调显示、音频、传感器输入与存储。','開發嵌入式互動邏輯，協調顯示、音訊、感測器輸入與儲存。'),tr('Implement and debug software on the device, progressing from an initial demonstration to an updated physical prototype.','在实机上实现与调试软件，从初代演示推进到迭代原型。','在實機上實作與除錯軟體，從初代展示推進到迭代原型。')],
    implementation:tr('The source includes FreeRTOS tasks, an interaction state machine, StreamBuffer media prefetching, and a mutex for SD access. QMI8658 motion input and RC522 card UIDs can trigger media behavior. SoftAP/TCP handles local media-file updates. These source modules describe the software; the short first-generation clip shows an earlier prototype.','源码包含 FreeRTOS 任务、交互状态机、StreamBuffer 媒体预读与 SD 访问互斥。QMI8658 动作输入和 RC522 卡片 UID 可触发媒体行为，SoftAP/TCP 用于局域网媒体文件更新。这些模块说明软件实现；初代短视频展示的是较早的原型版本。','原始碼包含 FreeRTOS 任務、互動狀態機、StreamBuffer 媒體預讀與 SD 存取互斥。QMI8658 動作輸入和 RC522 卡片 UID 可觸發媒體行為，SoftAP/TCP 用於區域網路媒體檔案更新。這些模組說明軟體實作；初代短片展示的是較早的原型版本。'),
    caption:tr('Updated physical prototype','迭代后的实物原型','迭代後的實物原型'),
    video:'badge-v1.mp4',videoCaption:tr('First-generation prototype · short demonstration','初代原型 · 短演示','初代原型 · 短片展示'),
  },
  {
    id:'tabletop-device',index:'02',kind:'tabletop',image:'tabletop-v1.jpg',
    title:tr('Interactive tabletop device','智能桌游交互设备','智慧桌遊互動裝置'),
    short:tr('Connecting game phases with sound and light, from firmware to physical prototypes.','让桌游阶段与声光反馈联动，贯通嵌入式控制和实物原型。','讓桌遊階段與聲光回饋連動，貫通嵌入式控制和實物原型。'),
    role:tr('Embedded software, wiring & system integration; project lead','嵌入式软件、布线与系统集成；项目负责人','嵌入式軟體、佈線與系統整合；專案負責人'),
    tags:tr(['Embedded control','Audio & LEDs','Integration'],['嵌入式控制','声光联动','系统集成'],['嵌入式控制','聲光連動','系統整合']),
    context:tr('An interactive device that links tabletop game phases with audio and lighting feedback. The work combines embedded control, hardware selection, wiring, and physical integration.','通过扬声器与灯带，将桌游阶段转化为声光反馈的交互设备。项目结合嵌入式控制、硬件选型、布线与结构集成。','透過揚聲器與燈帶，將桌遊階段轉化為聲光回饋的互動裝置。專案結合嵌入式控制、硬體選型、佈線與結構整合。'),
    contributions:[tr('Develop embedded software and speaker/LED control logic, and integrate wiring and the physical assembly.','负责嵌入式软件、扬声器与灯带控制逻辑，以及布线和结构集成。','負責嵌入式軟體、揚聲器與燈帶控制邏輯，以及佈線和結構整合。'),tr('Contribute to the host-side Agent design and coordinate product planning and hardware/software collaboration.','参与上位机 Agent 设计，统筹产品方案与软硬件协作。','參與上位機 Agent 設計，統籌產品方案與軟硬體協作。')],
    implementation:tr('The first and second prototypes document the device’s evolution. Sound output, lighting, and physical integration form the core technical story. The hardware gallery documents the development board, PCB layout material, and enclosure model used in integration.','第一代实物与第二代演示记录了设备的迭代。声音输出、灯光控制和实体集成构成主要技术内容。硬件图集记录集成过程中使用的开发板、PCB 布局资料与外壳模型。','第一代實物與第二代展示記錄了裝置的迭代。聲音輸出、燈光控制和實體整合構成主要技術內容。硬體圖集記錄整合過程中使用的開發板、PCB 佈局資料與外殼模型。'),
    outcome:tr('As project lead, I coordinated implementation and teamwork. The project received recognition from Xiangjiang Science and Technology Innovation Institute and an opportunity to be showcased there.','作为项目负责人，推进实现与团队协作。项目获得湘江科技创新院认可，并获得在该院展示的机会。','作為專案負責人，推進實作與團隊協作。專案獲得湘江科技創新院認可，並獲得在該院展示的機會。'),
    caption:tr('First-generation physical prototype','第一代实物原型','第一代實物原型'),video:'tabletop-v2.mp4',videoCaption:tr('Second-generation device demonstration','第二代设备演示','第二代裝置展示'),
    gallery:[['tabletop-board.jpg',tr('Development board used in integration','联调中使用的板卡','整合測試中使用的板卡')],['tabletop-layout.jpg',tr('PCB layout material','PCB 布局布线资料','PCB 佈局佈線資料')],['tabletop-model.png',tr('Second-generation enclosure model','第二代结构白模','第二代結構白模')]],
  },
  {
    id:'line-following-robot',index:'03',kind:'control',
    title:tr('Line-following robot','巡线小车','循線小車'),
    short:tr('A sensor-to-actuator control loop with PID wheel-speed control and serial interaction.','从传感器到执行器，集成 PID 轮速闭环与串口交互。','從感測器到致動器，整合 PID 輪速閉迴路與串列互動。'),
    role:tr('Electrical control, mechanical design & assembly','电控、机械设计与组装','電控、機械設計與組裝'),tags:['STM32','PID','PWM'],source:'https://github.com/titfly77-cyber/LINE-CAR',
    context:tr('A mobile robot combining line following, turning, distance sensing, and serial interaction. I worked on electrical control and mechanical design and assembly.','整合巡线、转向、测距和串口交互的小车。我负责电控与机械设计组装。','整合循線、轉向、測距和串列互動的小車。我負責電控與機械設計組裝。'),
    contributions:[tr('Integrate wheel encoders, motor control, digital line sensors, ultrasonic ranging, and MPU6050 orientation input.','集成轮速编码器、电机控制、数字巡线传感器、超声波测距与 MPU6050 姿态输入。','整合輪速編碼器、馬達控制、數位循線感測器、超音波測距與 MPU6050 姿態輸入。'),tr('Organize motion stages and operating modes, with serial commands, a buzzer, and OLED feedback.','组织行程阶段与运行模式，结合串口命令、蜂鸣器与 OLED 完成状态反馈。','組織行程階段與運行模式，結合串列命令、蜂鳴器與 OLED 完成狀態回饋。')],
    implementation:tr('On STM32F103C8, encoder feedback feeds separate wheel-speed PID controllers whose outputs drive PWM. Digital sensor conditions adjust target wheel speeds for line following. Ultrasonic thresholds control stopping and recovery; orientation and encoder information guide turning. The linked version uses PID speed control, separate from the ADRC bed-cleaning project.','在 STM32F103C8 上，编码器反馈进入左右轮 PID 速度控制器，输出驱动 PWM。数字传感器条件判断调整目标轮速完成巡线；超声波阈值控制停车与恢复，姿态与编码器信息辅助转向。链接中的版本采用 PID 调速，与 ADRC 扫床项目分别展示。','在 STM32F103C8 上，編碼器回授進入左右輪 PID 速度控制器，輸出驅動 PWM。數位感測器條件判斷調整目標輪速完成循線；超音波門檻控制停車與恢復，姿態與編碼器資訊輔助轉向。連結中的版本採用 PID 調速，與 ADRC 掃床專案分別展示。'),
    caption:tr('Control architecture illustration based on the project code','依据项目代码整理的控制结构示意','依據專案程式碼整理的控制結構示意'),
  },
  {
    id:'bed-cleaning-robot',index:'04',kind:'adrc',
    title:tr('Bed-cleaning robot','扫床机器人','掃床機器人'),
    short:tr('Electrical control for an automated bed-cleaning application, using ADRC.','面向自动扫床场景的电控实现，采用 ADRC 控制。','面向自動掃床場景的電控實作，採用 ADRC 控制。'),
    role:tr('Electrical control · ADRC','电控 · ADRC 控制','電控 · ADRC 控制'),tags:tr(['ADRC','Motion control'],['ADRC','运动控制'],['ADRC','運動控制']),
    context:tr('An automated machine designed for bed cleaning. My contribution focused on electrical control, using active disturbance rejection control (ADRC).','用于自动清扫床面的机器人。我负责电控部分，控制方案采用自抗扰控制（ADRC）。','用於自動清掃床面的機器人。我負責電控部分，控制方案採用自抗擾控制（ADRC）。'),
    contributions:[tr('Take responsibility for the electrical-control portion of the bed-cleaning robot.','负责扫床机器人的电控部分。','負責掃床機器人的電控部分。'),tr('Apply ADRC as the project’s control approach.','在该项目中采用 ADRC 控制方案。','在該專案中採用 ADRC 控制方案。')],
    implementation:tr('This project represents my ADRC control practice in an automated cleaning application. It is presented separately from the PID-based line-following robot.','该项目体现了在自动清扫应用中的 ADRC 控制实践，与采用 PID 的巡线小车分别展示。','該專案體現了在自動清掃應用中的 ADRC 控制實踐，與採用 PID 的循線小車分別展示。'),
    caption:tr('ADRC control practice · project overview','ADRC 控制实践 · 项目概览','ADRC 控制實踐 · 專案概覽'),
  },
  {
    id:'robot-arm',index:'05',kind:'arm',image:'robot-arm.jpg',
    title:tr('Robotic arm control','机械臂电控','機械手臂電控'),
    short:tr('Segmented motion control to move a robotic arm toward a target point.','采用分段式控制，让机械臂抵达目标点。','採用分段式控制，讓機械手臂抵達目標點。'),
    role:tr('Electrical control; mechanical work by a teammate','负责电控；机械部分由同伴完成','負責電控；機械部分由同伴完成'),tags:tr(['Motion control','Integration'],['运动控制','设备联调'],['運動控制','裝置整合測試']),
    context:tr('A robotic-arm experiment using segmented control to reach a target point. The work was shared: I handled electrical control and a teammate handled the mechanical portion.','通过分段式控制抵达目标点的机械臂实践。项目由团队分工完成：我负责电控，同伴负责机械部分。','透過分段式控制抵達目標點的機械手臂實踐。專案由團隊分工完成：我負責電控，同伴負責機械部分。'),
    contributions:[tr('Implement the electrical-control portion and work on device integration.','承担电控实现与设备联调。','承擔電控實作與裝置整合測試。')],
    implementation:tr('Segment the motion toward the target and validate the control behavior on the physical setup. The demonstration records the arm, connected control hardware, and development environment.','将抵达目标的运动分段控制，并在实物平台上验证控制行为。演示记录了机械臂、连接的控制硬件与开发环境。','將抵達目標的運動分段控制，並在實物平台上驗證控制行為。展示記錄了機械手臂、連接的控制硬體與開發環境。'),
    caption:tr('Frame from the hardware demonstration','硬件演示视频画面','硬體展示影片畫面'),video:'robot-arm.mp4',
  },
  {
    id:'tobacco-clearing',index:'06',kind:'tobacco',
    title:tr('Tobacco-stalk clearing machine','烟草秸秆智能清理机','菸草秸稈智慧清理機'),
    short:tr('Mechanical and electrical-control work for post-harvest stalk clearing.','面向烟草收割后的秸秆清理，承担机械与电控工作。','面向菸草收割後的秸稈清理，承擔機械與電控工作。'),
    role:tr('Mechanical & electrical control lead','机械与电控技术负责人','機械與電控技術負責人'),tags:tr(['Agricultural machinery','Electrical control'],['农业机械','电控'],['農業機械','電控']),
    context:tr('An agricultural machine for handling tobacco stalks after harvest. My work covered mechanical design and electrical control.','用于烟草收割后秸秆处理的农业机械。我承担机械设计及电控工作。','用於菸草收割後秸稈處理的農業機械。我承擔機械設計及電控工作。'),
    contributions:[tr('Work on overall structural modeling, transmission mechanisms, and cutter-roller design.','负责整机结构建模、传动机构与刀辊设计。','負責整機結構建模、傳動機構與刀輥設計。'),tr('Iterate low-level drive control and clearing-path plans.','迭代底层驱动与清理路径方案。','迭代底層驅動與清理路徑方案。')],
    implementation:tr('The project connects mechanical structure, transmission, and electrical control around the stalk-clearing task.','围绕秸秆清理任务，结合机械结构、传动与电控方案进行整机设计。','圍繞秸稈清理任務，結合機械結構、傳動與電控方案進行整機設計。'),
    outcome:tr('The project received RMB 50,000 in support from the Golden Seed Program and coverage from People’s Daily and Hunan Satellite TV. These are project-level outcomes.','项目获得“金种子计划”5 万元投资支持，并获人民日报、湖南卫视报道。上述成果归属于项目。','專案獲得「金種子計畫」5 萬元投資支持，並獲人民日報、湖南衛視報導。上述成果歸屬於專案。'),
    gallery:[['tobacco-team.jpg',tr('Project recognition and mentor photo','项目奖牌与导师合影','專案獎牌與導師合影')]],caption:tr('Agricultural machinery · project overview','农业机械 · 项目概览','農業機械 · 專案概覽'),
  },
  {
    id:'vision-access',index:'07',kind:'vision',
    title:tr('Face-vision access control','人脸视觉门禁系统','人臉視覺門禁系統'),
    short:tr('Linking edge-based face detection to a physical barrier actuator.','将边缘端人脸目标检测与门禁执行器动作连接起来。','將邊緣端人臉目標偵測與門禁致動器動作連接起來。'),
    role:tr('Edge vision & actuator integration','边缘视觉与执行器联动','邊緣視覺與致動器連動'),tags:['Raspberry Pi 5B','YOLOv8n'],
    context:tr('A vision-and-actuator project connecting face-target detection with an access-barrier mechanism.','将人脸目标检测与门禁栅栏机构连接起来的视觉和执行器联动项目。','將人臉目標偵測與門禁柵欄機構連接起來的視覺和致動器連動專案。'),
    contributions:[tr('Deploy YOLOv8n on Raspberry Pi 5B and build the real-time visual-processing chain.','在树莓派 5B 部署 YOLOv8n，搭建实时视觉处理链路。','在樹莓派 5B 部署 YOLOv8n，建立即時視覺處理鏈路。'),tr('Drive a servo over bus communication, linking visual outputs with barrier movement.','通过总线通信驱动舵机，使视觉结果与栅栏动作联动。','透過匯流排通訊驅動伺服馬達，使視覺結果與柵欄動作連動。')],
    implementation:tr('The key integration is the path from visual detection to physical action: image input, edge processing, a control decision, and servo movement.','重点是从视觉检测到物理动作的集成链路：图像输入、边缘处理、控制判断与舵机动作。','重點是從視覺偵測到物理動作的整合鏈路：影像輸入、邊緣處理、控制判斷與伺服馬達動作。'),caption:tr('Edge vision · project overview','边缘视觉 · 项目概览','邊緣視覺 · 專案概覽'),
  },
  {
    id:'drone-hardware',index:'08',kind:'drone',image:'drone-board.jpg',
    title:tr('Drone hardware practice','无人机硬件实践','無人機硬體實踐'),
    short:tr('Board revisions and soldering, with hands-on work on drone and controller hardware.','围绕无人机与遥控器硬件，完成改版与焊接实践。','圍繞無人機與遙控器硬體，完成改版與焊接實踐。'),
    role:tr('Hardware revisions & soldering','硬件改版与焊接','硬體改版與焊接'),tags:tr(['Hardware','PCB','Soldering'],['硬件','PCB','焊接'],['硬體','PCB','焊接']),
    context:tr('A practical hardware-learning project involving drone and remote-controller boards.','围绕无人机主体板与遥控器板开展的硬件能力提升项目。','圍繞無人機主體板與遙控器板開展的硬體能力提升專案。'),
    contributions:[tr('Work on hardware revisions and soldering for the device.','承担设备硬件改版与焊接工作。','承擔裝置硬體改版與焊接工作。')],
    implementation:tr('The board photographs document the physical hardware work. My contribution covers hardware revisions and soldering.','电路板照片记录了实际硬件工作。本项目中的个人贡献为硬件改版与焊接。','電路板照片記錄了實際硬體工作。本專案中的個人貢獻為硬體改版與焊接。'),caption:tr('Drone main board','无人机主体电路板','無人機主體電路板'),gallery:[['drone-controller.jpg',tr('Remote-controller board','遥控器电路板','遙控器電路板')]],
  },
  {
    id:'competition-control',index:'09',kind:'competition',
    title:tr('Electronics competition practice','模拟电赛控制实践','模擬電子競賽控制實踐'),
    short:tr('Control architecture, ADRC, and sensor integration in a collaborative development setting.','在协作开发中实践电控架构、ADRC 与传感器融合。','在協作開發中實踐電控架構、ADRC 與感測器融合。'),
    role:tr('Electrical architecture & motion control','电控架构与运动控制','電控架構與運動控制'),tags:tr(['ADRC','Sensor integration'],['ADRC','传感器融合'],['ADRC','感測器融合']),
    context:tr('An electronics-competition practice experience focused on the electrical-control architecture and embedded development.','围绕电控架构与嵌入式功能开发开展的模拟电赛实践。','圍繞電控架構與嵌入式功能開發開展的模擬電子競賽實踐。'),
    contributions:[tr('Design the electrical-control architecture and contribute ADRC, sensor-fusion, line-following, and obstacle-avoidance logic.','设计电控架构，编写 ADRC、传感器融合及巡线、避障逻辑。','設計電控架構，撰寫 ADRC、感測器融合及循線、避障邏輯。')],
    implementation:tr('Work with teammates to integrate embedded functions and validate the control logic. This experience is described separately from the linked PID line-following firmware.','与团队协同推进嵌入式功能集成和控制逻辑验证。该经历与已链接的 PID 巡线固件分别说明。','與團隊協同推進嵌入式功能整合和控制邏輯驗證。該經歷與已連結的 PID 循線韌體分別說明。'),caption:tr('Control engineering · practice overview','控制工程 · 实践概览','控制工程 · 實踐概覽'),
  },
];

export const skills = [
  {title:tr('Embedded software & peripherals','嵌入式软件与外设','嵌入式軟體與周邊'),body:tr('C · ESP32-S3 · FreeRTOS · state machines · media buffering · peripheral communication','C · ESP32-S3 · FreeRTOS · 状态机 · 媒体缓冲 · 外设通信','C · ESP32-S3 · FreeRTOS · 狀態機 · 媒體緩衝 · 周邊通訊'),project:'emotion-screen'},
  {title:tr('Motion control & sensing','运动控制与传感器','運動控制與感測器'),body:tr('STM32 · encoder feedback · PID wheel-speed control · ADRC · PWM · orientation sensing','STM32 · 编码器反馈 · PID 轮速控制 · ADRC · PWM · 姿态读取','STM32 · 編碼器回授 · PID 輪速控制 · ADRC · PWM · 姿態讀取'),project:'line-following-robot'},
  {title:tr('Computer vision & edge deployment','机器视觉与边缘部署','機器視覺與邊緣部署'),body:tr('Raspberry Pi 5B · YOLOv8n deployment · RK3588 interface testing · vision-to-actuator integration','树莓派 5B · YOLOv8n 部署 · RK3588 接口测试 · 视觉与执行器联动','樹莓派 5B · YOLOv8n 部署 · RK3588 介面測試 · 視覺與致動器連動'),project:'vision-access'},
  {title:tr('HMI & hardware integration','HMI 与软硬件联调','HMI 與軟硬體整合測試'),body:tr('Serial touchscreens · USART protocols · parameter updates · state synchronization · exception testing','串口屏 · USART 协议 · 参数下发 · 状态同步 · 异常测试','串列觸控螢幕 · USART 協定 · 參數下發 · 狀態同步 · 異常測試'),section:'experience'},
];
export const experiences = [
  {date:tr('AUG 2026 — PRESENT','2026.08 — 至今','2026.08 — 至今'),company:tr('Kangtong Electronics','长沙市康通电子科技有限公司','長沙市康通電子科技有限公司'),role:tr('AI fitness device · Algorithm interfaces & integration','AI 体锻机 · 算法接口与设备联调','AI 體鍛機 · 演算法介面與裝置整合測試'),body:tr('Test and debug RK3588-based YOLO-Face + ArcFace and MediaPipe Pose interfaces. Integrate camera hardware, reproduce recognition issues, and validate device behavior with the engineering team.','在 RK3588 平台开展 YOLO-Face + ArcFace 与 MediaPipe Pose 接口测试、摄像头硬件联调、识别问题复现和设备功能验证。','在 RK3588 平台開展 YOLO-Face + ArcFace 與 MediaPipe Pose 介面測試、攝影機硬體整合測試、辨識問題重現和裝置功能驗證。')},
  {date:tr('JUL — AUG 2026','2026.07 — 2026.08','2026.07 — 2026.08'),company:tr('Shenzhen Weier Technology','深圳市纬尔科技','深圳市緯爾科技'),role:tr('Cotton-topping robot · Embedded control & field integration','棉花打顶机器人 · 嵌入式与田间联调','棉花打頂機器人 · 嵌入式與田間整合測試'),body:tr('Contribute to STM32F4 cutting-sequence analysis, relating visual targets, wheel odometry, and IMU data to blade timing. Join field tests in Xinjiang and work with engineers on issue analysis and validation.','参与 STM32F4 切割时序分析，梳理视觉目标、轮速和 IMU 数据与刀片触发的关系；赴新疆进行田间联调，与工程师协作分析问题并验证。','參與 STM32F4 切割時序分析，梳理視覺目標、輪速和 IMU 資料與刀片觸發的關係；赴新疆進行田間整合測試，與工程師協作分析問題並驗證。')},
  {date:tr('JAN 2026','2026.01','2026.01'),company:tr('Shenzhen InnoX Academy','深圳科创学院','深圳科創學院'),role:tr('Robotics R&D · HMI software intern','机器人研发 · HMI 软件实习','機器人研發 · HMI 軟體實習'),body:tr('Independently develop a serial-touchscreen HMI, including controls, parameters, status, and alarms. Design the serial protocol following team discussions and validate state synchronization and communication exceptions on the device.','独立完成串口屏 HMI 开发，覆盖控制、参数、状态与报警。经团队讨论后独立设计串口协议，完成状态同步、通信异常测试与整机验证。','獨立完成串列觸控螢幕 HMI 開發，涵蓋控制、參數、狀態與警報。經團隊討論後獨立設計串列協定，完成狀態同步、通訊異常測試與整機驗證。')},
];
